### ISSUE TITLE
json-stat.js 0.12.1 is not the latest release

### ISSUE THREAD

**Issue by badosa** [eurostat/eurostat.js#1]
You are using [json-stat.js 0.12.1](https://github.com/eurostat/eurostat.js/blob/master/js/json-stat.js) but this is not the latest release. Please, update to [0.13.3](https://github.com/badosa/JSON-stat/blob/master/json-stat.js).

**Comment by jgaffuri** [comment]
OK, thanks for the info.
Do you know if json-stat is available under a CDN ?

**Comment by badosa** [comment]
Unfortunately json-stat is not available under a CDN.

**Comment by badosa** [comment]
json-stat is available under [jsDelivr](https://www.jsdelivr.com/).

JSON-stat Javascript Toolkit (JJT)
https://www.jsdelivr.com/package/npm/jsonstat

JSON-stat Javascript Utilities Suite (JJUS)
https://www.jsdelivr.com/package/npm/jsonstat-utils

**Comment by jgaffuri** [comment]
Brilliant !
And thanks a lot Xavier for the develoment of json-stat format and lib. We keep promoting its adoption !
