### ISSUE TITLE
Unnecessary Dataset(0)

### ISSUE THREAD

**Issue by badosa** [eurostat/eurostat.js#25]
In [line 172 in eurostat-map.js](https://github.com/eurostat/eurostat.js/blob/fbea69f7e7995785c68a990f8c667c5a27eeb6b4/js/eurostat-map.js#L172)

```js
out.statData_ = EstLib.jsonstatToIndex( JSONstat(data___).Dataset(0) );
```

can be rewritten as

```js
out.statData_ = EstLib.jsonstatToIndex( JSONstat(data___) );
```

That's because JSONstat(data___).class is already "dataset". Eurostat's API returns always a JSON-stat dataset, so there's no need to select the first one (that was common practice in JSON-stat <v.20 when the usual response was "bundle").

Also, this fragment in [L712](https://github.com/eurostat/eurostat.js/blob/fbea69f7e7995785c68a990f8c667c5a27eeb6b4/js/eurostat-map.js#L712) 

```js
for(var i=0; i<geos.length; i++) {
   var geoi = geos[i];
   ind[geoi] = jsData.Data({ geo : geoi });
}
```

can probably be simplified a little:

```js
for(var i=0; i<geos.length; i++) {
   ind[geos[i]] = jsData.Data(i);
}
```

**Comment by jgaffuri** [comment]
Thanks Xavier for your feedback ! I have implemented all your suggestions.

**Comment by badosa** [comment]
If you don't need to support very old browsers (and you probably don't because I noticed you are using Array methods like _Array.isArray()_) you can simplify even more the _jsonstatToIndex()_ function using _Array.map()_:

```js
function jsonstatToIndex(jsData) {
  var ind = {};
  jsData.Dimension("geo").id.map(function(e,i){
     ind[e] = jsData.Data(i);
  });
  return ind;
}
```

Or using arrow functions (that is, supporting only modern browsers):

```js
function jsonstatToIndex(jsData) {
   var ind = {};
   jsData.Dimension("geo").id.map((e,i)=>ind[e] = jsData.Data(i));
   return ind;
}
```
