### ISSUE TITLE
Export Map

### ISSUE THREAD

**Issue by uyc** [eurostat/eurostat.js#35]
Hi again,
Thank you very much for the answer you gave before. Is it possible to share with me a code to export maps preferably in "svg" (if not possible "png")? format.
Kind regards.

**Comment by jgaffuri** [comment]
Please not that the map component has now moved to https://github.com/eurostat/eurostat-map.js
There is a plan to provide SVG and PNG exports
- https://github.com/eurostat/eurostat-map.js/issues/24
- https://github.com/eurostat/eurostat-map.js/issues/15
Please check the next versions, and feel free to contribute.
